openapi:
  apartment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackge/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: i8c05JQsZA2hrJAa5u4K0gVYfRzahMh9ljGK%2FhsNk8ode%2FM%2FFl6BtYeMWec5gpkP1ZeZ9hG00PEkcFH3Y%2Bs0jA%3D%3D

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/oauth/redirect
      - http://192.168.0.144:5221/oauth/redirect
      - http://localhost:3000/oauth/redirect
file:
  dir: D:/download/greengram4/

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://192.168.0.161:3306/greengram5
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 231512412412512512
            clientSecret: 123412f12313541431
            scope:
              - email
              - profile
          facebook:
            clientId: 46634735624512
            clientSecret: 32523523642525add24
            scope:
              - email
              - public_profile
          naver:
            client-id: UYDLOVAXXtS7lvQhB53p
            client-secret: C5P95eBkNF
            #clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              # - profile_image
            client-name: Naver
          kakao:
            client-id: 06904354643a157cda43d72b3caff095
            client-secret: 0oYB2ZEi7vvoLk9mwGFCRdgmSV6bipMh
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8080

fcm:
  certification: serviceAccountKey.json


---

spring:
  config:
    activate:
      on-profile:   "prod1"


file:
  dir: /home/download/
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: "jpa"
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram5_jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    generate-ddl: true

---