openapi:
  apartment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackge/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: i8c05JQsZA2hrJAa5u4K0gVYfRzahMh9ljGK%2FhsNk8ode%2FM%2FFl6BtYeMWec5gpkP1ZeZ9hG00PEkcFH3Y%2Bs0jA%3D%3D

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000

file:
  dir: D:/download/greengram4/

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://192.168.0.161:3306/greengram4
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082

fcm:
  certification: serviceAccountKey.json


---

spring:
  config:
    activate:
      on-profile:   "prod1"


file:
  dir: /home/download/
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8082