openapi:
  apartment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackge/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: i8c05JQsZA2hrJAa5u4K0gVYfRzahMh9ljGK%2FhsNk8ode%2FM%2FFl6BtYeMWec5gpkP1ZeZ9hG00PEkcFH3Y%2Bs0jA%3D%3D

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000

file:
  dir: D:/download/greengram4/

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://192.168.0.161:3306/greengram5
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
          facebook:
            clientId:
            clientSecret:
            scope:
              - email
              - public_profile
          naver:
            client-id:
            client-secret:
            #clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              # - profile_image
            client-name: Naver
          kakao:
            client-id: cda26f7fed69daf12c76c17bbb6ac929
            client-secret: OjIGWqSdAvSMDeb1nNaTzokMHNz5Hiqr
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082

fcm:
  certification: serviceAccountKey.json


---

spring:
  config:
    activate:
      on-profile:   "prod1"


file:
  dir: /home/download/
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8082